apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: crud
spec:
  selector:
    app.k8s.io/name: todo-serive
  ports:
    - name: grpc
      protocol: TCP
      port: 6001
      targetPort: grpc
    - name: http
      protocol: TCP
      port: 6002
      targetPort: http
    - name: metric
      protocol: TCP
      port: 6443
      targetPort: metric
