development:
  dialect: sqlite3
  datasource: /tmp/samples/crud/todo.db
  dir: /tmp/samples/crud
test:
  dialect: mysql
  datasource: root:root@tcp(localhost:3306)/todo_service?parseTime=true
  dir: .
